# Complex flat scene with dense static obstacles for ROS2/Nav2 demos
# @package _group_

type: complex_flat_obstacles
name: complex_flat_obstacles_scene

ground_plane:
  enabled: true

obstacles:
  - type: box
    position: [2.0, 0.0, 0.35]
    size: [0.6, 3.5, 0.7]
  - type: box
    position: [-2.0, 0.0, 0.35]
    size: [0.6, 3.5, 0.7]
  - type: box
    position: [0.0, 2.4, 0.35]
    size: [3.5, 0.6, 0.7]
  - type: box
    position: [0.0, -2.4, 0.35]
    size: [3.5, 0.6, 0.7]
  - type: box
    position: [0.0, 0.0, 0.35]
    size: [0.8, 0.8, 0.7]
  - type: cylinder
    position: [3.5, 3.0, 0.45]
    radius: 0.4
    height: 0.9
  - type: cylinder
    position: [3.5, -3.0, 0.45]
    radius: 0.4
    height: 0.9
  - type: cylinder
    position: [-3.5, 3.0, 0.45]
    radius: 0.4
    height: 0.9
  - type: cylinder
    position: [-3.5, -3.0, 0.45]
    radius: 0.4
    height: 0.9
  - type: box
    position: [5.0, 0.0, 0.5]
    size: [0.6, 2.0, 1.0]
  - type: box
    position: [-5.0, 0.0, 0.5]
    size: [0.6, 2.0, 1.0]
