# Stairs scene for Go2 teleop demo
# @package _group_

type: stairs
name: stairs_scene

ground_plane:
  enabled: true

obstacles:
  - type: box
    position: [1.5, 0.0, 0.025]
    size: [0.4, 1.2, 0.05]
  - type: box
    position: [1.9, 0.0, 0.05]
    size: [0.4, 1.2, 0.10]
  - type: box
    position: [2.3, 0.0, 0.075]
    size: [0.4, 1.2, 0.15]
  - type: box
    position: [-1.0, 1.5, 0.25]
    size: [0.5, 0.5, 0.5]
